// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(schedule, ladder) {
    var dailyRanking, monthlyRanking, weekLadder, weeklyRanking;
    dailyRanking = new schedule.RecurrenceRule();
    dailyRanking.hour = 0;
    dailyRanking.minute = 1;
    dailyRanking.seconds = 0;
    weekLadder = schedule.scheduleJob(dailyRanking, function() {
      console.log("Updating the ladder for today.");
      ladder.createDailyLadder();
    });
    weeklyRanking = new schedule.RecurrenceRule();
    weeklyRanking.dayOfWeek = 1;
    weeklyRanking.hour = 0;
    weeklyRanking.minute = 1;
    weeklyRanking.seconds = 0;
    weekLadder = schedule.scheduleJob(weeklyRanking, function() {
      console.log("Updating the ladder for the past week.");
      ladder.createWeeklyLadder();
    });
    monthlyRanking = new schedule.RecurrenceRule();
    monthlyRanking.date = 1;
    monthlyRanking.hour = 1;
    monthlyRanking.minute = 0;
    monthlyRanking.seconds = 0;
    weekLadder = schedule.scheduleJob(monthlyRanking, function() {
      console.log("Updating the ladder for the past month.");
      ladder.createMonthlyLadder();
    });
  };

}).call(this);
