// Generated by CoffeeScript 1.7.1
(function() {
  var Game;

  Game = require("../app/models/game");


  /*
  Search through a REGEX in game list and return the result(s)
  @param  {string} search [the letters]
  @param  {Object} return [objects]
  @return {Callback}
   */

  module.exports = function(moment) {
    return {
      regexFind: function(search, done) {
        var regex;
        regex = new RegExp(search, "i");
        console.log(search + " => " + regex);
        return Game.find({
          title: regex
        }).sort({
          updated_at: -1
        }).sort({
          created_at: -1
        }).limit(5).exec(function(err, games) {
          var ret;
          if (err) {
            mailer.cLog('Error at ' + __filename, err);
          }
          if (!err) {
            ret = {
              data: games,
              go: 200
            };
          } else {
            ret = {
              data: JSON.stringify(err),
              go: 404
            };
          }
          return done(ret);
        });
      }
    };
  };

}).call(this);
