// Generated by CoffeeScript 1.7.1
(function() {
  var Game, moment;

  moment = require("moment");

  Game = require("../app/models/game");


  /*
  Search through a REGEX in game list and return the result(s)
  @param  {string} search [the letters]
  @param  {Object} return [objects]
  @return {Callback}
   */

  module.exports = {
    regexFind: function(search, done) {
      var regex;
      regex = new RegExp(search, "i");
      console.log(search + " => " + regex);
      Game.find({
        title: regex
      }).sort({
        updated_at: -1
      }).sort({
        created_at: -1
      }).limit(5).exec(function(err, games) {
        var ret;
        if (!err) {
          ret = {
            data: games,
            go: 200
          };
        } else {
          ret = {
            data: JSON.stringify(err),
            go: 404
          };
        }
        done(ret);
      });
    }
  };

}).call(this);
