// Generated by CoffeeScript 1.7.1
(function() {
  var OAuth2, auth, database, googleapis, oauth2Client;

  database = require("./database");

  auth = require("./auth");

  googleapis = require("googleapis");

  OAuth2 = googleapis.auth.OAuth2;

  oauth2Client = new OAuth2(database.google.client_email, database.google.client_secret, auth.cyf.domain);

  exports.googleUrl = function(url, callback) {
    googleapis.discover("urlshortener", "v1").execute(function(err, client) {
      oauth2Client.credentials = {
        access_token: database.google.access_token,
        refresh_token: database.google.refresh_token
      };
      client.urlshortener.url.insert({
        longUrl: url
      }).withAuthClient(oauth2Client).execute(function(err, result) {
        if (err) {
          console.log(err);
        }
        callback(result.id);
      });
    });
  };

}).call(this);
