// Generated by CoffeeScript 1.7.1
(function() {
  module.exports = function(io, Chat, moment) {
    return {
      alive: function() {
        return io.sockets.emit("alive", {
          date: moment().utc()
        });
      },
      glob: function(icon, text, desc) {
        return io.sockets.emit("globalevent", {
          icon: (icon ? icon : "fa fa-circle-o"),
          message: text,
          desc: (desc ? desc : ""),
          date: new Date
        });
      },
      connected: function(text) {
        return io.of('/chat').emit("newUser", {
          message: text,
          date: new Date
        });
      },
      discuss: function(user, message) {
        var chat, _t;
        _t = this;
        chat = new Chat();
        chat.user_from = user;
        chat.message = message;
        return chat.save(function(err, chat) {
          if (err) {
            console.log(err);
          }
          return _t.pushMessage(chat);
        });
      },
      pushMessage: function(message) {
        return io.of('/chat').emit("message", {
          user: message.user_from,
          message: message.message,
          date: message.dateSent
        });
      },
      onlineNumber: function(nb) {
        return io.of('/chat').emit("onlineUsers", {
          number: nb
        });
      }
    };
  };

}).call(this);
