// Generated by CoffeeScript 1.7.1
(function() {
  var badgeSchema, mongoose;

  mongoose = require("mongoose");

  badgeSchema = mongoose.Schema({
    ownedBy: [
      {
        type: mongoose.Schema.Types.ObjectId,
        index: true,
        ref: "User"
      }
    ],
    title: String,
    Description: String,
    dateCreation: {
      type: Date,
      "default": Date.now
    },
    requirement: [
      {
        reqType: String,
        reqValue: Number
      }
    ]
  });

  module.exports = mongoose.model("Badge", badgeSchema);

}).call(this);
