// Generated by CoffeeScript 1.7.1
(function() {
  var autoIncrement, badgeSchema, mongoose;

  mongoose = require("mongoose");

  autoIncrement = require('mongoose-auto-increment');

  autoIncrement.initialize(mongoose);

  badgeSchema = mongoose.Schema({
    ownedBy: [
      {
        type: mongoose.Schema.Types.ObjectId,
        index: true,
        ref: "User"
      }
    ],
    title: String,
    icon: {
      type: String,
      "default": 'undefined.png'
    },
    description: String,
    dateCreation: {
      type: Date,
      "default": Date.now
    },
    reqBadges: [
      {
        type: Number,
        ref: "Badge"
      }
    ],
    requirement: [
      {
        reqType: String,
        reqValue: Number
      }
    ]
  });

  badgeSchema.plugin(autoIncrement.plugin, 'Badge');

  module.exports = mongoose.model("Badge", badgeSchema);

}).call(this);
