// Generated by CoffeeScript 1.7.1
(function() {
  var chatSchema, mongoose;

  mongoose = require("mongoose");

  chatSchema = mongoose.Schema({
    user_from: {
      idCool: String,
      icon: String,
      pseudo: String,
      level: Number,
      dailyRank: Number,
      aclLevel: {
        type: Boolean,
        "default": 99
      }
    },
    message: String,
    dateSent: {
      type: Date,
      "default": Date.now
    }
  });

  module.exports = mongoose.model("Chat", chatSchema);

}).call(this);
