// Generated by CoffeeScript 1.7.1
(function() {
  var gameSchema, mongoose;

  mongoose = require("mongoose");

  gameSchema = mongoose.Schema({
    title: String,
    type: String,
    players: {
      type: Number,
      "default": 0
    },
    updated_at: {
      type: Date,
      "default": Date.now
    },
    created_at: {
      type: Date,
      "default": Date.now
    }
  });

  module.exports = mongoose.model("Game", gameSchema);

}).call(this);
